# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: airline_app.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='airline_app.proto',
  package='airline_app',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x61irline_app.proto\x12\x0b\x61irline_app\"\x1a\n\tSelection\x12\r\n\x05value\x18\x01 \x01(\t\"\x1d\n\nSysMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2\xdf\x01\n\x12\x41irlineApplication\x12@\n\x0b\x41irlineList\x12\x16.airline_app.Selection\x1a\x17.airline_app.SysMessage\"\x00\x12\x42\n\rAirlineReserv\x12\x16.airline_app.Selection\x1a\x17.airline_app.SysMessage\"\x00\x12\x43\n\x0e\x41irlineDisplay\x12\x16.airline_app.Selection\x1a\x17.airline_app.SysMessage\"\x00\x42\x37\n\x1cio.grpc.examples.airline_appB\x0f\x41irlineAppProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_SELECTION = _descriptor.Descriptor(
  name='Selection',
  full_name='airline_app.Selection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='airline_app.Selection.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=60,
)


_SYSMESSAGE = _descriptor.Descriptor(
  name='SysMessage',
  full_name='airline_app.SysMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='airline_app.SysMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=62,
  serialized_end=91,
)

DESCRIPTOR.message_types_by_name['Selection'] = _SELECTION
DESCRIPTOR.message_types_by_name['SysMessage'] = _SYSMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Selection = _reflection.GeneratedProtocolMessageType('Selection', (_message.Message,), dict(
  DESCRIPTOR = _SELECTION,
  __module__ = 'airline_app_pb2'
  # @@protoc_insertion_point(class_scope:airline_app.Selection)
  ))
_sym_db.RegisterMessage(Selection)

SysMessage = _reflection.GeneratedProtocolMessageType('SysMessage', (_message.Message,), dict(
  DESCRIPTOR = _SYSMESSAGE,
  __module__ = 'airline_app_pb2'
  # @@protoc_insertion_point(class_scope:airline_app.SysMessage)
  ))
_sym_db.RegisterMessage(SysMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\034io.grpc.examples.airline_appB\017AirlineAppProtoP\001\242\002\003HLW'))

_AIRLINEAPPLICATION = _descriptor.ServiceDescriptor(
  name='AirlineApplication',
  full_name='airline_app.AirlineApplication',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=94,
  serialized_end=317,
  methods=[
  _descriptor.MethodDescriptor(
    name='AirlineList',
    full_name='airline_app.AirlineApplication.AirlineList',
    index=0,
    containing_service=None,
    input_type=_SELECTION,
    output_type=_SYSMESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AirlineReserv',
    full_name='airline_app.AirlineApplication.AirlineReserv',
    index=1,
    containing_service=None,
    input_type=_SELECTION,
    output_type=_SYSMESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='AirlineDisplay',
    full_name='airline_app.AirlineApplication.AirlineDisplay',
    index=2,
    containing_service=None,
    input_type=_SELECTION,
    output_type=_SYSMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_AIRLINEAPPLICATION)

DESCRIPTOR.services_by_name['AirlineApplication'] = _AIRLINEAPPLICATION

# @@protoc_insertion_point(module_scope)
