# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import car_app_pb2 as car__app__pb2


class CarApplicationStub(object):
  """Services provided as List, Reserve and Display
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CarList = channel.unary_unary(
        '/car_app.CarApplication/CarList',
        request_serializer=car__app__pb2.Selection.SerializeToString,
        response_deserializer=car__app__pb2.SysMessage.FromString,
        )
    self.CarReserv = channel.unary_unary(
        '/car_app.CarApplication/CarReserv',
        request_serializer=car__app__pb2.Selection.SerializeToString,
        response_deserializer=car__app__pb2.SysMessage.FromString,
        )
    self.CarDisplay = channel.unary_unary(
        '/car_app.CarApplication/CarDisplay',
        request_serializer=car__app__pb2.Selection.SerializeToString,
        response_deserializer=car__app__pb2.SysMessage.FromString,
        )


class CarApplicationServicer(object):
  """Services provided as List, Reserve and Display
  """

  def CarList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CarReserv(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CarDisplay(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CarApplicationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CarList': grpc.unary_unary_rpc_method_handler(
          servicer.CarList,
          request_deserializer=car__app__pb2.Selection.FromString,
          response_serializer=car__app__pb2.SysMessage.SerializeToString,
      ),
      'CarReserv': grpc.unary_unary_rpc_method_handler(
          servicer.CarReserv,
          request_deserializer=car__app__pb2.Selection.FromString,
          response_serializer=car__app__pb2.SysMessage.SerializeToString,
      ),
      'CarDisplay': grpc.unary_unary_rpc_method_handler(
          servicer.CarDisplay,
          request_deserializer=car__app__pb2.Selection.FromString,
          response_serializer=car__app__pb2.SysMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'car_app.CarApplication', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
