# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hotel_app.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hotel_app.proto',
  package='hotel_app',
  syntax='proto3',
  serialized_pb=_b('\n\x0fhotel_app.proto\x12\thotel_app\"\x1a\n\tSelection\x12\r\n\x05value\x18\x01 \x01(\t\"\x1d\n\nSysMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2\xcb\x01\n\x10HotelApplication\x12:\n\tHotelList\x12\x14.hotel_app.Selection\x1a\x15.hotel_app.SysMessage\"\x00\x12<\n\x0bHotelReserv\x12\x14.hotel_app.Selection\x1a\x15.hotel_app.SysMessage\"\x00\x12=\n\x0cHotelDisplay\x12\x14.hotel_app.Selection\x1a\x15.hotel_app.SysMessage\"\x00\x42\x33\n\x1aio.grpc.examples.hotel_appB\rHotelAppProtoP\x01\xa2\x02\x03HLWb\x06proto3')
)




_SELECTION = _descriptor.Descriptor(
  name='Selection',
  full_name='hotel_app.Selection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='hotel_app.Selection.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=56,
)


_SYSMESSAGE = _descriptor.Descriptor(
  name='SysMessage',
  full_name='hotel_app.SysMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='hotel_app.SysMessage.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=87,
)

DESCRIPTOR.message_types_by_name['Selection'] = _SELECTION
DESCRIPTOR.message_types_by_name['SysMessage'] = _SYSMESSAGE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Selection = _reflection.GeneratedProtocolMessageType('Selection', (_message.Message,), dict(
  DESCRIPTOR = _SELECTION,
  __module__ = 'hotel_app_pb2'
  # @@protoc_insertion_point(class_scope:hotel_app.Selection)
  ))
_sym_db.RegisterMessage(Selection)

SysMessage = _reflection.GeneratedProtocolMessageType('SysMessage', (_message.Message,), dict(
  DESCRIPTOR = _SYSMESSAGE,
  __module__ = 'hotel_app_pb2'
  # @@protoc_insertion_point(class_scope:hotel_app.SysMessage)
  ))
_sym_db.RegisterMessage(SysMessage)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\032io.grpc.examples.hotel_appB\rHotelAppProtoP\001\242\002\003HLW'))

_HOTELAPPLICATION = _descriptor.ServiceDescriptor(
  name='HotelApplication',
  full_name='hotel_app.HotelApplication',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=90,
  serialized_end=293,
  methods=[
  _descriptor.MethodDescriptor(
    name='HotelList',
    full_name='hotel_app.HotelApplication.HotelList',
    index=0,
    containing_service=None,
    input_type=_SELECTION,
    output_type=_SYSMESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HotelReserv',
    full_name='hotel_app.HotelApplication.HotelReserv',
    index=1,
    containing_service=None,
    input_type=_SELECTION,
    output_type=_SYSMESSAGE,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='HotelDisplay',
    full_name='hotel_app.HotelApplication.HotelDisplay',
    index=2,
    containing_service=None,
    input_type=_SELECTION,
    output_type=_SYSMESSAGE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HOTELAPPLICATION)

DESCRIPTOR.services_by_name['HotelApplication'] = _HOTELAPPLICATION

# @@protoc_insertion_point(module_scope)
