# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import hotel_app_pb2 as hotel__app__pb2


class HotelApplicationStub(object):
  """Services provided as List, Reserve and Display
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.HotelList = channel.unary_unary(
        '/hotel_app.HotelApplication/HotelList',
        request_serializer=hotel__app__pb2.Selection.SerializeToString,
        response_deserializer=hotel__app__pb2.SysMessage.FromString,
        )
    self.HotelReserv = channel.unary_unary(
        '/hotel_app.HotelApplication/HotelReserv',
        request_serializer=hotel__app__pb2.Selection.SerializeToString,
        response_deserializer=hotel__app__pb2.SysMessage.FromString,
        )
    self.HotelDisplay = channel.unary_unary(
        '/hotel_app.HotelApplication/HotelDisplay',
        request_serializer=hotel__app__pb2.Selection.SerializeToString,
        response_deserializer=hotel__app__pb2.SysMessage.FromString,
        )


class HotelApplicationServicer(object):
  """Services provided as List, Reserve and Display
  """

  def HotelList(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HotelReserv(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def HotelDisplay(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HotelApplicationServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'HotelList': grpc.unary_unary_rpc_method_handler(
          servicer.HotelList,
          request_deserializer=hotel__app__pb2.Selection.FromString,
          response_serializer=hotel__app__pb2.SysMessage.SerializeToString,
      ),
      'HotelReserv': grpc.unary_unary_rpc_method_handler(
          servicer.HotelReserv,
          request_deserializer=hotel__app__pb2.Selection.FromString,
          response_serializer=hotel__app__pb2.SysMessage.SerializeToString,
      ),
      'HotelDisplay': grpc.unary_unary_rpc_method_handler(
          servicer.HotelDisplay,
          request_deserializer=hotel__app__pb2.Selection.FromString,
          response_serializer=hotel__app__pb2.SysMessage.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'hotel_app.HotelApplication', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
